### ISSUE TITLE
How to make it work with TkRuby?

### ISSUE THREAD

**Issue by krepkiy** [Largo/ocran#10]
Hello. It doesn't work for me with TkRuby.
Maybe someone knows how to make it work?

ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x64-mingw-ucrt]
tk (0.5.0)
ocran (1.3.15)

My file test_tk.rb
`require 'tk'
root = TkRoot.new { title "Ex1" }
TkLabel.new(root) {
  text  'Hello, World!'
  pack  { padx 55 ; pady 55; side 'left' }
}
Tk.mainloop`

option 1
`# ocran test_tk.rb --windows
=== Loading script to check dependencies
=== Attempting to trigger autoload of #<Class:Tk>::WinRegistry
=== Attempting to trigger autoload of #<Class:Tk>::ValidateConfigure
=== Attempting to trigger autoload of #<Class:Tk>::BinaryString
=== Attempting to trigger autoload of #<Class:Tk>::AUTO_PATH
=== Attempting to trigger autoload of #<Class:Tk>::Tile
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:2887:in `_invoke': can't invoke "font" command: application has been destroyed (RuntimeError)
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:2887:in `_invoke'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:1932:in `_ip_invoke_core'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:1965:in `_tk_call_core'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:1988:in `tk_call'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk/font.rb:126:in `<class:TkFont>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk/font.rb:9:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tkextlib/tile.rb:293:in `<module:Font>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tkextlib/tile.rb:281:in `<module:Tile>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tkextlib/tile.rb:113:in `<module:Tk>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tkextlib/tile.rb:112:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:518:in `const_get'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:518:in `block (3 levels) in attempt_load_autoload'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:514:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:514:in `block (2 levels) in attempt_load_autoload'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:512:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:512:in `block in attempt_load_autoload'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:506:in `loop'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:506:in `attempt_load_autoload'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:774:in `build_exe'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:1307:in `block in <top (required)>'`

option 2 (compiled done but not executed)
`# ocran test_tk.rb --windows --no-autoload
=== Loading script to check dependencies
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/error_highlight-0.5.1.gemspec for gem error_highlight-0.5.1
=== Detected gem error_highlight-0.5.1 (loaded, files)
===     0 files, 0 bytes
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/did_you_mean-1.6.3.gemspec for gem did_you_mean-1.6.3
=== Detected gem did_you_mean-1.6.3 (loaded, files)
===     0 files, 0 bytes
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/syntax_suggest-1.1.0.gemspec for gem syntax_suggest-1.1.0
=== Detected gem syntax_suggest-1.1.0 (loaded, files)
===     1 files, 111 bytes
=== Detected gem ocran-1.3.15 (loaded, files)
===     6 files, 284024 bytes
=== Detected gem tk-0.5.0 (loaded, files)
===     415 files, 2939900 bytes
=== Including 61 encoding support files (3775488 bytes, use --no-enc to exclude)
=== Building test_tk.exe
=== Adding user-supplied source files
=== Adding ruby executable rubyw.exe
=== Adding detected DLL C:/Ruby32-x64/bin/ruby_builtin_dlls/libgmp-10.dll
=== Adding detected DLL C:/Ruby32-x64/msys64/ucrt64/bin/tk86.dll
=== Adding detected DLL C:/Ruby32-x64/msys64/ucrt64/bin/tcl86.dll
=== Adding detected DLL C:/Ruby32-x64/bin/ruby_builtin_dlls/zlib1.dll
=== Adding detected DLL C:/Ruby32-x64/bin/ruby_builtin_dlls/libffi-8.dll
=== Adding external manifest C:/Ruby32-x64/bin/ruby_builtin_dlls/ruby_builtin_dlls.manifest
=== Adding library files
=== Compressing 16729037 bytes

LZMA 22.01 (x86) : Igor Pavlov : Public domain : 2022-07-15

Input size:  16729037 (15 MiB)
Output size: 4445085 (4 MiB)
=== Finished building test_tk.exe (4492721 bytes)`

option 3
`# ocran test_tk.rb --windows --no-autoload --debug
=== Loading script to check dependencies
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/error_highlight-0.5.1.gemspec for gem error_highlight-0.5.1
=== Detected gem error_highlight-0.5.1 (loaded, files)
===     0 files, 0 bytes
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/did_you_mean-1.6.3.gemspec for gem did_you_mean-1.6.3
=== Detected gem did_you_mean-1.6.3 (loaded, files)
===     0 files, 0 bytes
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/syntax_suggest-1.1.0.gemspec for gem syntax_suggest-1.1.0
=== Detected gem syntax_suggest-1.1.0 (loaded, files)
===     1 files, 111 bytes
=== Detected gem ocran-1.3.15 (loaded, files)
===     6 files, 284024 bytes
=== Detected gem tk-0.5.0 (loaded, files)
===     415 files, 2939900 bytes
=== Including 61 encoding support files (3775488 bytes, use --no-enc to exclude)
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:84:in `+': no implicit conversion of nil into String (TypeError)

      @path = sub(/(\.[^.]*?|)$/) { s.to_s + $1 }
                                             ^^
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:84:in `block in append_to_filename!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:88:in `sub'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:88:in `sub'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:84:in `append_to_filename!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:921:in `build_exe'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:1307:in `block in <top (required)>'`

**Comment by Largo** [comment]
require 'tk' 
root = TkRoot.new { title "Ex1" }
 TkLabel.new(root) { text  'Hello, World!' 
pack  { padx 55 ; pady 55; side 'left' } } 
Tk.mainloop unless defined?(Ocran)

Can you try this? I'm believe it attempts to open the TK window, but at this time ocran just exits.
Can you check the tk.rb in the samples folder. I need to look into this.

**Comment by Largo** [comment]
@shinokaro maybe In the second example something goes wrong at ocra.rb:84.

**Comment by krepkiy** [comment]
> require 'tk' root = TkRoot.new { title "Ex1" } TkLabel.new(root) { text 'Hello, World!' pack { padx 55 ; pady 55; side 'left' } } Tk.mainloop unless defined?(Ocran)
> 
> Can you try this? I'm believe it attempts to open the TK window, but at this time ocran just exits. Can you check the tk.rb in the samples folder. I need to look into this.

# ocran test_tk.rb --windows
=== Loading script to check dependencies
=== Attempting to trigger autoload of #<Class:Tk>::WinRegistry
=== Attempting to trigger autoload of #<Class:Tk>::ValidateConfigure
=== Attempting to trigger autoload of #<Class:Tk>::BinaryString
=== Attempting to trigger autoload of #<Class:Tk>::AUTO_PATH
=== Attempting to trigger autoload of #<Class:Tk>::Tile
=== Attempting to trigger autoload of #<Class:Tk>::Text
=== Attempting to trigger autoload of #<Class:Tk>::Grid
=== WARNING: #<Class:Tk>::Grid was defined autoloadable, but caused NameError
=== Attempting to trigger autoload of #<Class:Tk>::Pack
=== WARNING: #<Class:Tk>::Pack was defined autoloadable, but caused NameError
=== Attempting to trigger autoload of #<Class:Tk>::Place
=== WARNING: #<Class:Tk>::Place was defined autoloadable, but caused NameError
=== Attempting to trigger autoload of #<Class:Tk>::Button
=== Attempting to trigger autoload of #<Class:Tk>::Canvas
=== Attempting to trigger autoload of #<Class:Tk>::CheckButton
=== Attempting to trigger autoload of #<Class:Tk>::Entry
=== Attempting to trigger autoload of #<Class:Tk>::Frame
=== Attempting to trigger autoload of #<Class:Tk>::LabelFrame
=== Attempting to trigger autoload of #<Class:Tk>::Listbox
=== Attempting to trigger autoload of #<Class:Tk>::Menu
=== Attempting to trigger autoload of #<Class:Tk>::OptionMenBbutton
=== WARNING: #<Class:Tk>::OptionMenBbutton was defined autoloadable, but caused NameError
=== Attempting to trigger autoload of #<Class:Tk>::Message
=== Attempting to trigger autoload of #<Class:Tk>::PanedWindow
=== Attempting to trigger autoload of #<Class:Tk>::Scale
=== Attempting to trigger autoload of #<Class:Tk>::Scrollbar
=== Attempting to trigger autoload of #<Class:Tk>::Spinbox
=== Attempting to trigger autoload of #<Class:Tk>::Toplevel
=== Attempting to trigger autoload of #<Class:Tk>::Clock
=== Attempting to trigger autoload of #<Class:Tk>::OptionObj
=== Attempting to trigger autoload of #<Class:Tk>::Fontchooser
=== Attempting to trigger autoload of #<Class:Tk>::MacResource
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:1930:in `_invoke': can't find package resource (RuntimeError)
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:1930:in `_ip_invoke_core'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:1965:in `_tk_call_core'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:1992:in `tk_call_without_enc'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk/macpkg.rb:42:in `<module:MacResource>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk/macpkg.rb:31:in `<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:518:in `const_get'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:518:in `block (3 levels) in attempt_load_autoload'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:514:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:514:in `block (2 levels) in attempt_load_autoload'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:512:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:512:in `block in attempt_load_autoload'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:506:in `loop'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:506:in `attempt_load_autoload'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:774:in `build_exe'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/ocran-1.3.15/bin/ocran:1307:in `block in <top (required)>'

**Comment by shinokaro** [comment]
> @shinokaro maybe In the second example something goes wrong at ocra.rb:84.

I've fixed this issue: https://github.com/Largo/ocran/commit/07895c759837f5592c9afbaf56f4c19a7539d1f0

**Comment by shinokaro** [comment]
> from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk/macpkg.rb:42:in <top (required)>'

tk/macpkg" is a package for Macintosh. Will this work with the following command?

`ocran test_tk.rb --windows --gem-spec=tk --no-autoload`

**Comment by Largo** [comment]
Okay, thank you very much. I will gladly make a new release when we figure this out. Note: the newest TK libs don't work with the TK gem yet! 

I'm planning to set up wine for this and also attempt to make some automated test. I'm currently working on ruby.wasm, but will get back to this soon!

**Comment by krepkiy** [comment]
> ocran test_tk.rb --windows --gem-spec=tk --no-autoload

compiled done but not executed

ocran test_tk.rb --windows --gem-spec=tk --no-autoload                                                             
=== Loading script to check dependencies                                                                             
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/error_highlight-0.5.1.gemspe
c for gem error_highlight-0.5.1                                                                                      
=== Detected gem error_highlight-0.5.1 (loaded, files)                                                               
===     0 files, 0 bytes                                                                                             
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/did_you_mean-1.6.3.gemspec f
or gem did_you_mean-1.6.3                                                                                            
=== Detected gem did_you_mean-1.6.3 (loaded, files)                                                                  
===     0 files, 0 bytes                                                                                             
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/syntax_suggest-1.1.0.gemspec
 for gem syntax_suggest-1.1.0                                                                                        
=== Detected gem syntax_suggest-1.1.0 (loaded, files)                                                                
===     1 files, 111 bytes                                                                                           
=== Detected gem ocran-1.3.15 (loaded, files)                                                                        
===     6 files, 284024 bytes                                                                                        
=== Detected gem tk-0.5.0 (spec)                                                                                     
=== WARNING: ext/tk/extconf.rb was not found                                                                         
=== WARNING: ext/tk/tkutil/extconf.rb was not found                                                                  
===     0 files, 0 bytes                                                                                             
=== Including 61 encoding support files (3775488 bytes, use --no-enc to exclude)                                     
=== Building test_tk.exe                                                                                             
=== Adding user-supplied source files                                                                                
=== Adding ruby executable rubyw.exe                                                                                 
=== Adding detected DLL C:/Ruby32-x64/bin/ruby_builtin_dlls/libgmp-10.dll                                            
=== Adding detected DLL C:/Ruby32-x64/msys64/ucrt64/bin/tk86.dll                                                     
=== Adding detected DLL C:/Ruby32-x64/msys64/ucrt64/bin/tcl86.dll                                                    
=== Adding detected DLL C:/Ruby32-x64/bin/ruby_builtin_dlls/zlib1.dll                                                
=== Adding detected DLL C:/Ruby32-x64/msys64/ucrt64/lib/reg1.3/tclreg13.dll                                          
=== Adding detected DLL C:/Ruby32-x64/bin/ruby_builtin_dlls/libffi-8.dll                                             
=== Adding external manifest C:/Ruby32-x64/bin/ruby_builtin_dlls/ruby_builtin_dlls.manifest                          
=== Adding library files                                                                                             
=== Compressing 13508217 bytes                                                                                       
                                                                                                                     
LZMA 22.01 (x86) : Igor Pavlov : Public domain : 2022-07-15                                                          
                                                                                                                     
Input size:  13508217 (12 MiB)                                                                                       
Output size: 3640752 (3 MiB)                                                                                         
=== Finished building test_tk.exe (3688388 bytes)

**Comment by Largo** [comment]
@krepkiy Thanks for your patience. I confirmed that it works with the following command:

ocran tk.rb --windows --gem-full=tk --add-all-core --no-autoload

How to reproduce. See below or tk.rb in samples.

```shell
gem install tk
```

```ruby
require 'tk'
root = TkRoot.new { title "Hello, World!" }
TkLabel.new(root) do
   text 'Hello, World!'
   pack { padx 15 ; pady 15; side 'left' }
end
Tk.mainloop unless defined?(Ocran)
```


@shinokaro

**Comment by krepkiy** [comment]
**@Largo** Thank you for trying to help me. But this option doesn't work for me either.

**Comment by Largo** [comment]
Sorry, I can't work on this today, but I would recommend to try the following:

- Checkout this repository or download as zip.
- checkout the tk example in the sample folder folder
- try to run ocran according to the comment in that file. Make sure to use the newest ocran code instead of the installed gem ("ruby bin/ocran" instead of "ocran") and the parameters written in the file.

It's possible that the problem is elsewhere. Also make sure the antivirus is not interfering or try on a different machine.

**Comment by krepkiy** [comment]
**@Largo**

> Sorry, I can't work on this today, but I would recommend to try the following:
> 
> * Checkout this repository or download as zip.
> * checkout the tk example in the sample folder folder
> * try to run ocran according to the comment in that file. Make sure to use the newest ocran code instead of the installed gem ("ruby bin/ocran" instead of "ocran") and the parameters written in the file.
> 
> It's possible that the problem is elsewhere. Also make sure the antivirus is not interfering or try on a different machine.

I try on another machine but the result is the same. I don't understand one point about which you wrote.

> Make sure to use the newest ocran code instead of the installed gem ("ruby bin/ocran" instead of "ocran")

I don't understand how to put the updated code ocran. 
I put gem in the standard way gem install ocran
Sorry for my stupidity.

**Comment by krepkiy** [comment]
I downloaded the file ocran https://github.com/Largo/ocran/blob/master/bin/ocran
and copied it to the folder with the installed Ruby on my computer
c:\Ruby32-x64\lib\ruby\gems\3.2.0\gems\ocran-1.3.15\bin\

```
# ocran test_tk.rb --windows --gem-full=tk --add-all-core --no-autoload
=== Loading script to check dependencies
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/error_highlight-0.5.1.gemspec for gem error_highlight-0.5.1
=== Detected gem error_highlight-0.5.1 (loaded, files)
===     0 files, 0 bytes
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/did_you_mean-1.6.3.gemspec for gem did_you_mean-1.6.3
=== Detected gem did_you_mean-1.6.3 (loaded, files)
===     0 files, 0 bytes
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/syntax_suggest-1.1.0.gemspec for gem syntax_suggest-1.1.0
=== Detected gem syntax_suggest-1.1.0 (loaded, files)
===     1 files, 111 bytes
=== Detected gem ocran-1.3.15 (loaded, files)
===     7 files, 328819 bytes
=== Detected gem tk-0.5.0 (scripts, files, extras)
===     1060 files, 6597534 bytes
=== Including 61 encoding support files (3775488 bytes, use --no-enc to exclude)
=== Will include all ruby core libraries
=== Building test_tk.exe
=== Adding user-supplied source files
=== Adding ruby executable rubyw.exe
=== Adding detected DLL C:/Ruby32-x64/bin/ruby_builtin_dlls/libgmp-10.dll
=== Adding detected DLL C:/Ruby32-x64/msys64/ucrt64/bin/tcl86.dll
=== Adding detected DLL C:/Ruby32-x64/msys64/ucrt64/bin/tk86.dll
=== Adding detected DLL C:/Ruby32-x64/bin/ruby_builtin_dlls/zlib1.dll
=== Adding detected DLL C:/Ruby32-x64/msys64/ucrt64/lib/reg1.3/tclreg13.dll
=== Adding detected DLL C:/Ruby32-x64/bin/ruby_builtin_dlls/libffi-8.dll
=== Adding external manifest C:/Ruby32-x64/bin/ruby_builtin_dlls/ruby_builtin_dlls.manifest
=== Adding library files
=== Compressing 28788248 bytes
=== Finished building test_tk.exe (6879696 bytes)
```

when i run the file test_tk.exe I get the following error
![error](https://github.com/Largo/ocran/assets/5646727/47538e0c-b10a-407c-9d5c-c8ddaa3bf9b0)

**Comment by krepkiy** [comment]
Hi, friends!
I downloaded the repository as zip
and unzipped to c:\Ruby32-x64\lib\ruby\gems\3.2.0\gems\ocran-master
Execute the following commands in this folder:
```
# gem build ocran.gemspec
   Successfully built RubyGem
   Name: ocran
   Version: 1.3.15
   File: ocran-1.3.15.gem

# gem install ocran-1.3.15.gem
Successfully installed ocran-1.3.15
Parsing documentation for ocran-1.3.15
Installing ri documentation for ocran-1.3.15
Done installing documentation for ocran after 0 seconds
1 gem installed
```
Then in the C:\Ruby32-x64\bin folder
ran the command:
```
# ocran tk.rb --windows --gem-full=tk --add-all-core --no-autoload
=== Loading script to check dependencies
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/error_highlight-0.5.1.gemspec for gem error_highlight-0.5.1
=== Detected gem error_highlight-0.5.1 (loaded, files)
=== 0 files, 0 bytes
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/did_you_mean-1.6.3.gemspec for gem did_you_mean-1.6.3
=== Detected gem did_you_mean-1.6.3 (loaded, files)
=== 0 files, 0 bytes
=== Using default specification C:/Ruby32-x64/lib/ruby/gems/3.2.0/specifications/default/syntax_suggest-1.1.0.gemspec for gem syntax_suggest-1.1.0
=== Detected gem syntax_suggest-1.1.0 (loaded, files)
=== 1 files, 111 bytes
=== Detected gem ocran-1.3.15 (loaded, files)
=== 3 files, 167675 bytes
=== Detected gem tk-0.5.0 (scripts, files, extras)
=== 1060 files, 6597534 bytes
=== Including 61 encoding support files (3775488 bytes, use --no-enc to exclude)
=== Will include all ruby core libraries
=== Building tk.exe
ERROR: Stub image not available
```
I received the error ERROR: Stub image not available
What does this error mean? And how to fix it?
Thank you!

**Comment by Largo** [comment]
Hey @krepkiy 

It means that the stub.exe file wasn't built inside the gem...  It should be built automatically when you do what you did there. 

However, have you tried Ocran 1.3.14?

**Comment by krepkiy** [comment]
I tried version 1.3.14
It compiled done but also not executed
Could you build a new version of gem 1.3.16 with all the changes?

**Comment by Largo** [comment]
Sorry, seems like tk doesn't work with ocran 1.3.16

if you know the path of init.tcl maybe it helps if you include it in the command

```powershell
\tk.exe
C:/Users/Andre/AppData/Local/Temp/ocran1D15E4118731/lib/ruby/gems/3.3.0/gems/tk-0.5.0/lib/tk.rb:32:in `initialize': Can't find a usable init.tcl in the following directories:  (RuntimeError)
    C:/Users/Andre/AppData/Local/Temp/ocran1D15E4118731/msys64/ucrt64/lib/tcl8.6 C:/Users/Andre/AppData/Local/Temp/ocran1D15E4118731/lib/tcl8.6 C:/Users/Andre/AppData/Local/Temp/lib/tcl8.6 C:/Users/Andre/
This probably means that Tcl wasn't installed properly.
```

**Comment by krepkiy** [comment]
**Largo**
Thanks for the help, but I've never been able to get it to work

**Comment by krepkiy** [comment]
Hi guys. Is it possible to still make Ocran work with TkRuby? I still have hope that it is possible. Thanks.
