### ISSUE TITLE
The converted in .exe game doesn

### ISSUE THREAD

**Issue by Alihusejn** [Largo/ocran#16]

**Comment by Alihusejn** [comment]
Hi, I tried to convert this game https://github.com/dtcristo/raycaster in standalone executable and got this:
C:/Users/usr/AppData/Local/Temp/ocr474E.tmp/gemhome/gems/gosu-1.4.6/lib/gosu/compat.rb:71:in `initialize': While opening C:/Users (RuntimeError)ocal/Temp/ocr474E.tmp/assets/texture.png, the following error occured: The system cannot find the path specified.
        from C:/Users/usr/AppData/Local/Temp/ocr474E.tmp/gemhome/gems/gosu-1.4.6/lib/gosu/compat.rb:71:in `initialize'
        from C:/Users/usr/AppData/Local/Temp/ocr474E.tmp/src/raycaster/camera.rb:14:in `new'
        from C:/Users/usr/AppData/Local/Temp/ocr474E.tmp/src/raycaster/camera.rb:14:in `initialize'
        from C:/Users/usr/AppData/Local/Temp/ocr474E.tmp/src/raycaster/window.rb:12:in `new'
        from C:/Users/usr/AppData/Local/Temp/ocr474E.tmp/src/raycaster/window.rb:12:in `initialize'
        from C:/Users/usr/AppData/Local/Temp/ocr474E.tmp/src/raycaster.rb:13:in `new'
        from C:/Users/usr/AppData/Local/Temp/ocr474E.tmp/src/raycaster.rb:13:in `<main>'

**Comment by preetpalS** [comment]
You probably did not include the assets directory when you used this gem. Try appending "assets/texture.png" to the command you used already (see https://github.com/Largo/ocran?tab=readme-ov-file#additional-files-and-resources).

**Comment by Alihusejn** [comment]
Yeah, it worked after "ocran lib/raycaster.rb assets/texture.png". Thank you!
